# List out all of the directories containing images used in the training scheme
training_dirs:
  - 'data/raw/cropandweed-dataset/data/images'
  - 'data/raw/grass-clover-dataset/synthetic_images/synthetic_images/images'
  - 'data/raw/grass-clover-dataset/developed_images/developed_images/developed/ATV'
  - 'data/raw/grass-clover-dataset/developed_images/developed_images/developed/sony'
  - 'data/raw/grass-clover-dataset/developed_images/developed_images/developed/nikon'
  - 'data/raw/regen-pgc-view'
out_path: 'metadata/dataset_norm.json'