# List out all of the directories containing images used in the training scheme
training_dirs:
  - 'data/processed/labeled/images'
  - 'data/processed/unlabeled/images'
out_path: 'metadata/dataset_norm.json'