# Training configs
general:
  run_name: model_run_name
hardware:
  device: 'cuda'
directories:
  train_dir: 
  val_dir:
  test_dir:
  output_dir:
  chkpt_dir:
model:
  model_name: deeplabv3
  weight_decay: 1e-5
  filter_bias_and_bn: True
  ema: True # Exponential moving average of model parameters
  ema_decay: 0.999
  num_classes: 10
  in_channels: 3
  encoder_name: resnet18
  encoder_weights: imagenet
  encoder_depth: 5
optimizer:
  optim_name: sgd
  lr: 0.001
  momentum: 0.99
  beta1:
  beta2:
  nesterov: True

