# Training configs
general:
  run_name: model_run_name
hardware:
  device: 'cuda'
directories:
  train_l_dir: 'data/dev_data/labeled/train'
  train_u_dir: 'data/dev_data/unlabeled/train'
  val_dir: 'data/dev_data/labeled/val'
  test_dir: 'data/dev_data/labeled/test'
  output_dir: 'outputs'
  chkpt_dir:
model:
  model_name: deeplabv3
  weight_decay: 1e-5
  filter_bias_and_bn: True
  ema: True # Exponential moving average of model parameters
  ema_decay: 0.999
  num_classes: 10
  in_channels: 3
  encoder_name: resnet18
  encoder_weights: imagenet
  encoder_depth: 5
  lab_bs: 2
  unlab_bs: 4
optimizer:
  optim_name: sgd
  lr: 0.001
  momentum: 0.99
  beta1:
  beta2:
  nesterov: True

