# Training configs
run_name: model_run_name
device: 'cpu'
directories:
  train_l_dir: 'data/dev_data/labeled/train'
  train_u_dir: 'data/dev_data/unlabeled/train'
  val_dir: 'data/dev_data/labeled/val'
  test_dir: 'data/dev_data/labeled/test'
  output_dir: 'outputs'
  chkpt_dir:
model:
  model_name: deeplabv3
  num_classes: 2
  in_channels: 3
  encoder_name: resnet18
  encoder_weights: imagenet
  encoder_depth: 5
  lab_bs: 2
  unlab_bs: 2
  resize: [1000, 1000]
  epochs: 10
optimizer:
  name: SGD
  weight_decay: 0.00001
  filter_bias_and_bn: True
  ema: True # Exponential moving average of model parameters
  ema_decay: 0.999
  lr: 0.001
  momentum: 0.99
  beta1:
  beta2:
  nesterov: True
loss:
  name: DiceLoss
  mode: multiclass # binary or multiclass
  ignore_index: -1
  smooth: 0.0
  alpha: 0.5
  beta: 0.5
  gamma: 2
  eps: 0.0000001
  per_image: False
fixmatch:
  tau: [.85]
  # tau: [.5, .5, .5, .5, .5, .5, .5, .5, .5, .5] # One float threshold value per class
  lam: 0.2 # Scaling factor for loss function


